### ISSUE TITLE
`Socket hang up` when sending metrics

### ISSUE THREAD

**Issue by Defman** [Unleash/unleash-edge#550] opened 2024-10-04 13:48 UTC
### Describe the bug

When node send metrics to the edge server the socket hangs up.

### Logs, error output, etc.

```
ECONNRESET
Error: socket hang up
    at Socket.socketOnEnd (node:_http_client:535:25)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

```bash
http.error_message
"socket hang up"
	
http.error_name	
"Error"
	
http.method	
"POST"
	
http.target	
"/api/client/metrics"
	
http.url	
"http://unleash-edge.unleash-edge/api/client/metrics"
```
No errors in unleash

```


### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

Unleash edge version v19.4.1

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

node unleash-client v6.1.1

**Comment by chriswk** [comment] 2024-10-08 07:47
Sorry. I need more information to help you here. 

I can't reproduce using the 19.4.1 docker image and the current node client connected to demo. The client seems to post metrics fine.

Checklist:
1. The endpoint looks correct (/api/client/metrics) so I'm assuming you've instantiated with unleashUrl set to ${EDGE_URL}/api
2. Does your client actually receive the features?
3. Judging from the domain, you're running in kubernetes, have you verified that your traffic rules allows POST from where you're running your SDK to the Edge namespace?

**Comment by Defman** [comment] 2024-10-08 08:31
- [x] 1. The endpoint is indeed set to `{HOSTNAME}/api`
- [x] 2. Our application does indeed receives features and most metrics are propagated to the edge and back to hosted unleash ~600.000 in the last 48h.
- [x] 3. Since we are the application can receive features and post most metric I would imagine that there are no errors in our configuration.

The error seems very intermittent, since we are receiving features and posting a large portion of the metrics. It could perhaps be an intermittent error with kube-proxy.

**Comment by chriswk** [comment] 2024-10-10 08:34
Hmm. Good, at least you're getting metrics, but intermittent socket hangups in a server side application doesn't sound optimal.

Some curiosity to make sure our data sizes aren't harming us. 

This issue might be more suited on the unleash-client-node repository. There might be something in how make-fetch-happen (the http client in use) interacts with cluster services. This is more likely to be a client side problem or in infrastructure than an Edge problem.

Are you seeing anything on the Edge side when you're seeing these connection resets? Also, having a look at kube-proxy logs to dig further might be a good idea.

**Comment by chriswk** [comment] 2024-10-22 07:32
Closing due to staleness. Feel free to reopen if you have new information.

**Closed by chriswk** 2024-10-22 07:32 UTC
Labels: bug
